---
## mon
#

- name: Writing host key to known hosts
  shell: "ssh-keyscan -H {{ item }} >> /home/vagrant/.ssh/known_hosts"
  with_items: "{{ groups.all }}"

- name: Installing python prerquirements
  yum:
    name: python-setuptools
    state: present
  become: True

- name: Installing Ceph Deploy package
  yum:
    name: ceph-deploy
    state: present
  become: True

- name: Installing packages with ceph-deploy
  command: ceph-deploy install {{ item }}
  with_items: "{{ groups.all }}"

- name: Creating new Ceph cluster
  command: ceph-deploy --overwrite-conf new {{ item }}
  with_items: "{{ groups.mons }}"

- name: Initializing mon
  command: ceph-deploy --overwrite-conf mon create-initial

- name: Copying config file and admin key to ceph daemons
  command: ceph-deploy --overwrite-conf admin {{ item }}
  with_items: "{{ groups.all }}"
  when: item != "admin"

- name: Deploying mgr
  command: ceph-deploy mgr create {{ item }}
  with_items: "{{ groups.mgrs }}"

- name: Creating osds for device /dev/sdb
  command: ceph-deploy osd create --data /dev/sdb {{ item }}
  with_items: "{{ groups.osds }}"

- name: Creating osds for device /dev/sdc
  command: ceph-deploy osd create --data /dev/sdc {{ item }}
  with_items: "{{ groups.osds }}"

- name: Move ceph config and keyrings
  command: cp ceph.* /etc/ceph/
  become: True