---
- hosts:
    - admin
    - mgrs
    - mons
    - osds
  become: True
  roles:
    - common

- hosts:
    - admin
  roles:
    - admin

# - hosts:
#    - mons
#   become: True
#   roles:
#   - mons

# - hosts: osds
#   become: True
#   roles:
#   - osds

# - hosts:
#    - mons
#   vars:
#     dnsmasq_listen_address: 127.0.0.1
#   become: True
#   tags: rgw
#   roles:
#   - rgw
