---
## Common to all nodes
#

- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Adding ceph to YUM repo
  template:
    src: roles/common/templates/ceph.repo.j2
    dest: /etc/yum.repos.d/ceph.repo
    owner: root
    group: root
    mode: 0644

- name: Disable & Stop firewalld
  service:
    name: firewalld
    state: stopped
    enabled: False

- name: Disable SELinux
  selinux:
    state: disabled
